steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:latest', './eco_project/backend']
- name: 'ubuntu'
  args: ['cp', '-a', 'eco_project/backend/static/.', 'eco_project/frontend/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:latest', './eco_project/frontend']
images:
- 'gcr.io/$PROJECT_ID/backend:latest'
- 'gcr.io/$PROJECT_ID/frontend:latest'
